- include: prepare_permissions.yml
- include: clone.yml
- include: setup_env.yml
- include: test_server_specific.yml
- include: production_specific.yml
- include: dependencies.yml
- block:
      - include: upgrade.yml
  always:
      - include: systemd.yml
