- become: yes
  stat:
      path: "{{ project_dir }}/requirements.txt"
  register: requirements_file

- name: Install python packages (only if requirements.txt present in repository)
  become: yes
  pip:
      requirements: "{{ project_dir }}/requirements.txt"
  when: requirements_file.stat.exists == True

- name: Execute pre-deployment tasks
  become: yes
  shell: "cd {{ project_dir }} && {{ make_executable }} deployment_pre APP_USER={{deploy_user}} APP_GROUP_ID={{deploy_group_id}} HOME=/home/{{deploy_user}}"
