- name: Get group id of the deployment group
  shell: "getent group {{deploy_group}} | awk -F: '{printf \"%d\", $3}'"
  register: deploy_user_group_id_output

- set_fact:
    deploy_group_id: "{{ deploy_user_group_id_output.stdout }}"
