- name: "Copy '{{ systemd_service_name }}' systemd service"
  become: yes
  template:
      src: "systemd/{{ systemd_service_name }}.service.j2"
      dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
      owner: root
      group: root
      mode: 0640

- name: "Enable '{{ systemd_service_name }}' at system startup"
  become: yes
  systemd:
      state: restarted
      name: "{{ systemd_service_name }}"
      daemon_reload: yes
      enabled: yes
