- name: systemd_service_sleep must be greather than zero
  assert:
    that:
      - systemd_service_sleep > 0

- name: compose_env_name cannot be empty
  assert:
    that:
      - compose_env_name != ''

- name: Copy until-compose-env-running script
  become: yes
  copy:
      src: usr/local/bin/until-compose-env-running
      dest: /usr/local/bin/until-compose-env-running
      mode: "+x"

- name: "Copy '{{ systemd_service_name }}' systemd service"
  become: yes
  template:
      src: "systemd/project.service.j2"
      dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
      owner: root
      group: root
      mode: 0640

- name: "Enable '{{ systemd_service_name }}' at system startup"
  become: yes
  systemd:
      state: started
      name: "{{ systemd_service_name }}"
      daemon_reload: yes
      enabled: yes

- name: "Restart {{ systemd_service_name }}"
  become: yes
  systemd:
      state: restarted
      name: "{{ systemd_service_name }}"
  when: avoid_whole_environment_restart|bool == False
