- name: "Set up .env for test server"
  become: yes
  become_user: "{{ deploy_user|default('technical') }}"
  lineinfile:
      path: "{{ project_dir }}/.env"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items: "{{ test_specific_env }}"
      #- { line: "GIT_PASSWORD={{ git_password }}", regexp: '^GIT_PASSWORD', title: 'env: GIT read-only password' }
      #- { line: "DOMAIN_SUFFIX=.iwa-test", regexp: '^DOMAIN_SUFFIX', title: 'env: Add domain suffix' }
  when: inventory_hostname == "localhost"
